package tests;// Generated by Selenium IDE

import model.ContactData;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Random;

public class ContactRemovalTest extends TestBase{

    @Test
    public void CanRemoveContact() {
        if (app.contacts().getCountContact() == 0) {
            app.contacts().create(new ContactData("", "Java", "Tester", "Russia", "111222333", "test@mail.ru", ""));
        }
        var oldContacts = app.contacts().getListContact();
        var rnd = new Random();
        var index = rnd.nextInt(oldContacts.size());
        app.contacts().remove(oldContacts.get(index));
        var newContacts = app.contacts().getListContact();
        var expectedList = new ArrayList<>(oldContacts);
        expectedList.remove(index);
        Assertions.assertEquals(newContacts, expectedList);
    }

    @Test
    void CanRemoveAllContactOnce() {
        if (app.contacts().getCountContact() == 0) {
            app.contacts().create(new ContactData("", "firstname", "lastname", "address", "phone", "email", ""));
        }
        app.contacts().removeAllContact();
        Assertions.assertEquals(0, app.contacts().getCountContact());
    }
}

