package tests;// Generated by Selenium IDE

import model.ContactData;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;

public class ContactRemovalTest extends TestBase{

    @Test
    public void CanRemoveContact() {
        openContactPage();
        if (!isGroupPresent()) {
            driver.findElement(By.linkText("add new")).click();
            createContact(new ContactData("Java", "Tester", "Russia", "111222333", "test@mail.ru"));
        }
        removeGroup();
    }
}

