package tests;// Generated by Selenium IDE

import model.ContactData;
import org.junit.jupiter.api.Test;

public class ContactCreationTest extends TestBase{

    @Test
    public void CanCreateContact() {
        app.contacts().createContact(new ContactData("Java", "Tester", "Russia", "111222333", "test@mail.ru"));
    }

}
